### ISSUE TITLE
bodyParser 方法存在判断问题

### ISSUE THREAD

**Issue by Xiaobei-QuQ** [Koatty/koatty_payload#3]
```
 let body = ctx.getMetaData("_body");
if (!helper.isTrueEmpty(body)) {
    return body;
}

```
getMetaData方法默认不存在，返回空数组。函数isTrueEmpty不判断空数组情况，直接return 空数组。导致Post请求解析参数永远为 [] 。

**Comment by richenlin** [comment]
感谢! 稍后我们会修复

**Comment by richenlin** [comment]
已修复 koatty_payload@1.3.11

请升级该包，或者升级框架版本到 koatty@3.5.15

**Comment by hanrea** [comment]
最新的示例（自动生成模板）获取不到参数

**Comment by hanrea** [comment]
获取到的 body 类型为
__proto__:Array(0)
__proto__:Object
length:0

isTrueEmpty判断body 不为空，所以直接通过
下面测试是通过的（POST传json）不知是否匹配其他特殊情况：
if (!helper.isTrueEmpty(body) && (helper.isArray(body) && body.length > 0)) {

**Comment by hanrea** [comment]
@richenlin

**Comment by richenlin** [comment]
犯了一个低级错误😅
