### ISSUE TITLE
已修复 koatty_payload@1.3.11

### ISSUE THREAD

**Issue by hanrea** [Koatty/koatty_payload#4]
已修复 koatty_payload@1.3.11

请升级该包，或者升级框架版本到 koatty@3.5.15

_Originally posted by @richenlin in https://github.com/Koatty/koatty_payload/issues/3#issuecomment-1034564812_

这个修复有问题，示例已经跑不通了。无法获取任何参数

**Comment by richenlin** [comment]
抱歉给您造成困扰，已经紧急发布补丁

koatty_payload@1.3.16


后续我们会增加测试用例覆盖避免

**Comment by hanrea** [comment]
没事的，现在比较缺demo，人气再热点就好了
